# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 19, 13, 34, 27, 628487, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 19, 13, 34, 32, 388482, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
